"""añadido fila is_billing_default

Revision ID: 8478539da416
Revises: b2e967aba0d5
Create Date: 2024-06-05 23:17:51.982330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8478539da416'
down_revision = 'b2e967aba0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_billing_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('is_billing_default')

    # ### end Alembic commands ###
