"""cambios is_matriculate

Revision ID: bed8eb01fbcf
Revises: ac8d30fe326d
Create Date: 2024-06-12 11:32:22.136668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed8eb01fbcf'
down_revision = 'ac8d30fe326d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_matriculate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_matriculate')

    # ### end Alembic commands ###
