"""Migración primera de la base de datos

Revision ID: fe95415c35b2
Revises: 
Create Date: 2024-05-16 13:39:30.516475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe95415c35b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uq_name', sa.String(length=80), nullable=False),
    sa.Column('uq_descripcion', sa.String(length=200), nullable=False),
    sa.Column('imagen', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_descripcion'),
    sa.UniqueConstraint('uq_name')
    )
    op.create_table('concursantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uq_name', sa.String(length=80), nullable=False),
    sa.Column('uq_descripcion', sa.String(length=200), nullable=False),
    sa.Column('imagen', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_descripcion'),
    sa.UniqueConstraint('uq_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('uq_email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('concursantes')
    op.drop_table('chef')
    # ### end Alembic commands ###
