export const programasContent = [
    {
      id: 1,
      image: "src/front/img/img_programa/programa1.jpg",
      title: 'Programa 1',
      description: 'Los amantes de la cocina demuestran su talento ante un implacable jurado, preparando sus mejores creaciones para los comensales más exigentes.',
      duration: '03:13:29',
    },
    {
      id: 2,
      image: "src/front/img/img_programa/programa2.jpg",
      title: 'Programa 2',
      description: 'Los aspirantes se enfrentan al desafío de componer un plato que les transporte a sus orígenes. En la eliminación deben elaborar un espectacular postre.',
      duration: '03:23:45',
    },
    {
      id: 3,
      image: "src/front/img/img_programa/programa3.jpg",
      title: 'Programa 3',
      description: 'Los concursantes cocinan en las condiciones más adversas para todo un ejército o para las más ilustres personalidades en entornos únicos.',
      duration: '03:36:10',
    },
    {
      id: 4,
      image: "src/front/img/img_programa/programa4.jpg",
      title: 'Programa 4',
      description: 'Se pone en juego el pin de la inmunidad,  privilegio que pueden utilizar cuando más necesiten. El primer reto consiste en hacer un plato con pescado y la soja marina.',
      duration: '02:59:37',
    },
    {
      id: 5,
      image: "src/front/img/img_programa/programa5.jpg",
      title: 'Programa 5',
      description: 'Al llegar a las cocinas, los aspirantes encuentran alimentos habituales de nuestra cocina, pero con algo en común: su extraordinario tamaño.',
      duration: '03:08:35',
    },
    {
      id: 6,
      image: 'src/front/img/img_programa/programa6.jpg',
      title: 'Programa 6',
      description: 'Los aspirantes trabajan por relevos y el jurado se acerca a comprobar el plato para que el siguiente aspirante tome el relevo y cocine el siguiente plato.',
      duration: '03:19:47',
    },
    {
      id: 7,
      image: "src/front/img/img_programa/programa7a.jpg",
      title: 'Programa 7',
      description: 'Los aspirantes ponen rumbo a Oviedo, donde aspirantes y exaspirantes cocinan un menú firmado por el chef Nacho Manzano que catan 110 importantes personalidades.',
      duration: '03:14:25',
    },
    {
      id: 8,
      image: "src/front/img/img_programa/programa8.jpg",
      title: 'Programa 8',
      description: 'Los aspirantes deberán seducir a través de sus platos con algunos ingredientes afrodisiacos como protagonistas.',
      duration: '02:50:00',
    },
    {
      id: 9,
      image: 'src/front/img/img_programa/programa9.jpg',
      title: 'Programa 9',
      description: 'Los delantales negros se enfrentarán a la batalla de los sentidos. Donde cocinarán de forma sucesiva los platos que les indiquen los jueces.',
      duration: '03:20:73',
    },
  ];